version: '3.0'

services:
  localstack:
    image: localstack/localstack-pro:latest
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LOCALSTACK_API_KEY=1Y5gXaMouG
    ports:
      - '4566-4597:4566-4597'
